### ISSUE TITLE
Backup private keys

### ISSUE THREAD

**Issue by JackBekket** [MoonSHRD/Web3wallet#17]
Backup private keys, get pk of user, when he got **authorisation**

More info TBA

**Comment by JackBekket** [comment]
1. Create user *device wallet file* when he register(?)
wallet file can be secured by password or pincode, when created.  Note that this password protect only from unauthorised access for *device*, not *account steal*
Method's can be found at MainActivity

2.  Store user wallet at Backend. There are two way's for doing so:
a. store wallet *file*
b. store private key *string*

Note, that **wallet file is protected with user password** . On other hand private key give full access to user funds **without password**. 
Those means that, if we store **file** - we have additional protection for funds, cause, even if file has been stealed, it's still protected with user password. 
Pitfall - if user forgot password / pincode - it's deadlock. Nobody can recover access to funds without password, ever.

If we store private key - we have no additional protection from unauthorised recovery, and we need to **additionally encrypt private key string** at backend, to protect it.

3. Recover user wallet in process of Auth
3.1. if we store private key - we should get this string from backend by HTTPS
3.2. recover wallet file from private key at client side - use object `credentials` and method for recovery file from private key string
3.3. add additional check if wallet file is already stored at user device and there are no need for recovery.

**Comment by JackBekket** [comment]
@JackBekket По авторизации @ChronosX @TonyLead 

Создал ишью на сохранение и восстановление пользовательского кошелька

Можно считать это первым шагом по интеграции платежки, авторизации и приложения

**Comment by ChronosXYZ** [comment]
@JackBekket Backend part is done. It remains for me to make a deployment of my authorization service so that @TonyLead can begin to integrate authorization on the client side.

**Comment by JackBekket** [comment]
@ChronosX88 Decent! Glad to hear that!
